version: "1.0"

services:
  app:
    image: webdevops/php-nginx:8.2
    ports:
      - "80:80"
    working_dir: /app
    volumes:
      - ./:/app
      - storage-data:/app/storage
      - bootstrap-cache:/app/bootstrap/cache
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MAX_EXECUTION_TIME=300
    command: >
      bash -c "
        composer install --no-interaction --prefer-dist &&
        npm install &&
        npm run build &&
        php artisan key:generate --force &&
        php artisan storage:link &&
        chown -R application:application /app/storage /app/bootstrap/cache
      "

volumes:
  storage-data:
  bootstrap-cache:
